
export default new Map([
    ['flower', '../../../../assets/images/icons/icon_flower.png'],
    ['rule', '../../../../assets/images/icons/icon_rule.png'],
    ['edit', '../../../../assets/images/icons/icon_edit.png'],
    ['favourite', '../../../../assets/images/icons/icon_favourite.png'],
    ['home', '../../../../assets/images/icons/icon_home.png'],
    ['house', '../../../../assets/images/icons/icon_house.png'],
    ['love', '../../../../assets/images/icons/icon_love.png'],
    ['school', '../../../../assets/images/icons/icon_school.png'],
    ['hi', '../../../../assets/images/icons/icon_hi.png'],
    ['chart', '../../../../assets/images/icons/icon_chart.png'],
    ['ido', '../../../../assets/images/icons/icon_ido.png'],
    ['subway', '../../../../assets/images/icons/icon_subway.png'],
    ['girl', '../../../../assets/images/icons/icon_girl.png'],
    ['boy', '../../../../assets/images/icons/icon_boy.png'],
    ['user', '../../../../assets/images/my/profile.png'],
    ['close', '../../../../assets/images/icons/icon_close.png'],
    ['right_arrow', '../../../../assets/images/right_arrow.png'],
])